name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: python -m pip install -r requirements.txt
      - name: Compilation
        run: make
      - name: Import
        env:
          CSANIM_COMPILE: "y"
          CSANIM_IGNORE_FFMPEG: "y"
        run: python -c "import src"

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check
        run: |
          python3 ./tests/formatting.py

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: pip install sphinx sphinx-rtd-theme
      - name: Install csanim
        env:
          PYPI_VERSION: "0.0.1"
        run: |
          make wheel
          make install
      - name: Build docs
        env:
          CSANIM_QUIET: "y"
          CSANIM_COMPILE: "y"
          CSANIM_IGNORE_FFMPEG: "y"
        run: |
          cd ./docs
          mkdir ./_static ./_templates
          make html SPHINXOPTS="-W --keep-going"
