name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: python -m pip install -r requirements.txt
      - name: Compilation
        run: make
      - name: Import
        run: python -c "import src"

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check
        run: |
          python3 ./tests/formatting.py

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: pip install sphinx sphinx-rtd-theme
      - name: Install csanim
        env:
          PYPI_VERSION: 0.0.1
        run: |
          make wheel
          cd ./build/dist
          pip install csanim-0.0.1-py3-none-any.whl
      - name: Build docs
        env:
          CSANIM_COMPILE: asdf
        run: |
          cd ./docs
          mkdir ./_static ./_templates
          make html SPHINXOPTS="-W --keep-going"
